import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  SignUpButton,
  UserButton
} from "@clerk/nextjs";
import classNames from "classnames";
import { type Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navigation from "./components/navigation";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="min-h-dvh">
        <body
          className={classNames(
            geistSans.variable,
            geistMono.variable,
            "antialiased min-h-dvh flex flex-col"
          )}
        >
          <header className="sticky top-0 left-0 right-0 bg-gray-100 flex justify-between">
            <Navigation />
            <div className="flex gap-2">
              <SignedOut>
                <SignUpButton mode="modal">
                  <button className="text-blue-500">Register</button>
                </SignUpButton>
                <SignInButton mode="modal">
                  <button className="text-blue-500">Login</button>
                </SignInButton>
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </div>
          </header>
          <main className="grow">{children}</main>
          <footer className="sticky top-0 left-0 right-0 bg-gray-500">
            Footer
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
